### ISSUE TITLE
loaders not being respected

### ISSUE THREAD

**Issue by jjl** [sysgears/mochapack#1]
Hi, I'm a brand new user, so I'm probably doing something wrong, but when trying to use purs-loader, I get errors about misunderstood syntax because my purescript hasn't gone through the loader. 

Invocation: `./node_modules/mochapack/bin/mochapack --webpack-config webpack.config.test.js --webpack-env test`

However, running `webpack --config webpack.config.test.js --env test` completes fine, so it looks like my loaders are set up correctly.

Happy to help debug etc.

**Comment by vlasenko** [comment]
@jjl Yeah, okay. We need more details. It would be the best if we will be able to reproduce the issue ouselves. Can you set up a repo on GitHub that reproduces this issue and post url to it here?

**Comment by vlasenko** [comment]
@jjl Closing, due to no response from issue opener
