### ISSUE TITLE
[Bug] Can't install dependencies of the project

### ISSUE THREAD

**Issue by BeeMargarida** [sysgears/mochapack#122]
- [X] I'd be willing to submit the fix, if someone explains to me the need for `.pinyarn.js`

**Describe the bug**

After cloning the project it returns the error below when trying to install with `yarn`. If we install with `npm` but then try `npm test`, the same error happens:

![image](https://user-images.githubusercontent.com/25725586/150965132-c112bd19-101e-4c2e-ae1d-3976a6e3ca86.png)

**To Reproduce**

1. Clone the project
2. Install the dependencies with `yarn`
3. See the error

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Linux (Manjaro)
 - Node version: Tried with 14 and 12, same error
 - Mochapack: from the master branch

**Additional context**

I suppose it is locking to a yarn version that simply does not exist

**Comment by larixer** [comment]
@BeeMargarida Fixed via: #123
