### ISSUE TITLE
Implement --forbid-only

### ISSUE THREAD

**Issue by fgordillo** [sysgears/mochapack#14]
Mocha has an option --forbid-only:
`--forbid-only              Fail if exclusive test(s) encountered     [boolean]`

I tried to use it in mochapack by adding that flag to `mochapack.opts` but I guess it's not implemented yet. Is there any workaround for this?

**Comment by JamesMcMahon** [comment]
Implemented in https://github.com/sysgears/mochapack/pull/30/commits/21d880966554a77d9791861cee6c09d12099bc2b.

This can be closed.
