### ISSUE TITLE
Compilation succeeds but test finish immediately 

### ISSUE THREAD

**Issue by MrHKang** [sysgears/mochapack#2]
I have the same issue with [Compilation succeeds but test finish immediately ](https://github.com/zinserjan/mocha-webpack/issues/278), can you provide a successful demo to show? thank you very much.

**Comment by vlasenko** [comment]
@MrHKang Νο, it is not the way open source projects are done. It is your responsibility to provide demo and reproduction steps what is not working for you, not project maintainers.

**Comment by vlasenko** [comment]
Closing this issue because issue author did not provide reproduction steps
