### ISSUE TITLE
Yargs dependency leads to vulnerable mem package

### ISSUE THREAD

**Issue by dirkroorda** [sysgears/mochapack#22]
The current `"yargs": "^11.0.0"` dependency has in turn a dependency on 
`"os-locale": "^2.0.0",` which in turn is dependent on 
`"mem": "^1.1.0"` which is vulnerable.

It seems that the only wayout is: bump the version of `"yargs"` to at least 12.0.0 but 13 is better.

Many thanks for adopting the stale mocha-webpack, by the way.

**Comment by vlasenko** [comment]
@dirkroorda Yep, would you mind submitting PR?

**Comment by vlasenko** [comment]
@dirkroorda If upgrading `yargs` will lead to issues, we can use `package.json -> resolutions` instead

**Comment by dirkroorda** [comment]
> @dirkroorda Yep, would you mind submitting PR?

Well, I barely am able to get webpack configured, I do not feel competent to dive into this.

**Comment by vlasenko** [comment]
Okay, no worries :) I'll handle this

**Comment by vlasenko** [comment]
@dirkroorda Done, published `mochapack@1.1.2`
