### ISSUE TITLE
[Bug] importing of vue.js components

### ISSUE THREAD

**Issue by 271ch** [sysgears/mochapack#38]
- [ ] I'd be willing to submit the fix

**Describe the bug**

1) If I run the test `npm run test` I get a compilation error. It seams to me that the babel/ES6 is not loaded. I fear that mochapack does not use the webpack configuration :
```
  "scripts": {
    "build": "webpack --env=dev",
    "buildDev": "webpack --env=dev",
    "buildProd": "webpack --env=prod",
    "test": "mochapack --webpack-env=dev --webpack-config webpack.config.js --require test/setup.js test/**/*.spec.js"
  },
```
2) If I remove the component-file ending `vue` in `/test/MyTest.spec.js` line 18, I get another error because the file is not found. This seams also to lead to a non complete loading of the webpack configuration of the package (since in my package I can skip the `vue` ending)

**To Reproduce**

1)
```
git clone https://github.com/271ch/fomantic-ui-vue.git
git checkout add-test
npm run test
```
2)
 In `/test/MyTest.spec.js`, line 18, remove the component-file ending `.vue` , and then 
```
npm run test
```

**Screenshots**

With `vue` anding:
![image](https://user-images.githubusercontent.com/56249288/66739197-7ea4fb00-ee70-11e9-91e5-3443dfb854bd.png)

Without `vue` ending:
![image](https://user-images.githubusercontent.com/56249288/66739159-62a15980-ee70-11e9-8821-3deeb4200472.png)

**Environment if relevant (please complete the following information):**

 - Linux
 - Node version v10.16.3
 - Mochapack version 1.1.5
 - Webpack version 4.41.0

**Comment by vlasenko** [comment]
@271ch 
1. You forgot to pass `resolve -> extensions` webpack option, hence Webpack doesn't try to check `.vue` ending by default
2. This seems not a bug of `mochapack`, because adding `options: { prettify: false }` to `vue-loader` rule, "fixes" it. I'm not 100% sure, but it looks like a bug with `prettier` or `vue-loader`

**Comment by vlasenko** [comment]
@271ch The link to relevant `vue-loader` docs section:
https://github.com/vuejs/vue-loader/blob/master/docs/options.md#prettify
