### ISSUE TITLE
re-clone mocha-webpack repo?

### ISSUE THREAD

**Issue by alecf** [sysgears/mochapack#4]
there is a lot of useful blame history that could be used from the `mocha-webpack` repo - is there a reason you dropped all the git history?

**Comment by vlasenko** [comment]
@alecf No reason, I just cloned and commited. I can re-clone and push last commit with renamings, because to be able to publish package to npm it should have different name.

**Comment by vlasenko** [comment]
@alecf Well, I don't know how to do it now. Do you have any hints?

**Comment by akosipax** [comment]
Wouldn't forking a repository and renaming the repository do it?

**Comment by alecf** [comment]
nice! I just saw the mocha 6 work, really looking forward to it!

here's what I've just done in an effort to get the git history plus the mocha 6 support:

1) forked the original mocha-webpack repo into my own, just using the github `fork` button: https://github.com/alecf/mochapack
2) applied all of @vlasenko 's changes to support mocha 6

What I'd like to suggest @vlasenko does: remove this repo, fork my repo (using the fork button) into a fresh repo, still called `mochapack`. Then URLs and NPM will still all resolve to the same repo. Thoughts?

**Comment by vlasenko** [comment]
I'm not sure why to do it? I don't need previous history that much for development, only in very rare cases. And even if someone needs it, there is always the original repo:
https://github.com/zinserjan/mocha-webpack
I am afraid that the initial impression for the people if the repo is showing up as a fork is that the repo has only some minor bugfix and thats, as it is the case with 99% of the forks on GitHub. I want to avoid that initial impression.

**Comment by alecf** [comment]
as for any long running software project, the history is valuable in uncovering the reasoning behind implementation decisions, fixing regressions that may have plagued the code before, the ability to ask individuals questions who worked on issues in the code, etc.. basic software forensics. this is the whole reason for version control in the first place. 

Throwing out the history just because you want to reduce confusion about forking seems like "throwing out the baby with the bathwater" so to speak.

As an example of a project where this has become invaluable, see the original https://github.com/lloyd/node-memwatch project, which was forked and fixed many times before a reliable maintainer was found - but you can trace this lineage and learn the various false starts around memory tracking by reading the history and doing git blame on its curren incarnation, https://github.com/airbnb/node-memwatch

A few possible things can happen here:
 * people see the old repo, but do NOT see forks, so they never find `mochapack`. They submit PRs that go unseen.
 * someone else comes along and forks it beside yourself, now if improvements make their way into that repo, it becomes near impossible to bring those improvements together, because you can't merge cleanly, because you don't  know the basis of *your* fork

**Comment by vlasenko** [comment]
> as for any long running software project, the history is valuable in uncovering the reasoning behind implementation decisions, fixing regressions that may have plagued the code before, the ability to ask individuals questions who worked on issues in the code, etc.. basic software forensics. this is the whole reason for version control in the first place.

99% of the `mocha-webpack` was written by its original author and he is out of reach, so no way to know his reasoning other then looking into the code and original repository issues and PRs, and they are not copied when forking. So you will still need to go to original repository on GitHub and look. 

> Throwing out the history just because you want to reduce confusion about forking seems like "throwing out the baby with the bathwater" so to speak.

I am not against moving the original history to this repo, just not the way you are proposing. The way you are proposing to have the original history in this repo leads to problems with people confusion. And for me copying original history is not a priority. If someone comes up with the sequence of Git commands how to do it, I will do it at ANY point of time. I just don't want to spend time on this.

> A few possible things can happen here:
>
> * people see the old repo, but do NOT see forks, so they never find `mochapack`. They submit PRs that go unseen.

I will see them in original repo. So they will not go unseen.

> * someone else comes along and forks it beside yourself, now if improvements make their way into that repo, it becomes near impossible to bring those improvements together, because you can't merge cleanly, because you don't  know the basis of _your_ fork

It is open source and everyone can make a fork. It is not related to git history at all

**Comment by akosipax** [comment]
Hey @vlasenko, I believe this set of git commands will work (thanks to @alecf for the repo and I didn't have to figure out how to apply the changes). 

```
git clone https://github.com/alecf/mochapack.git

# remove origin which is currently alecf's repo
// optional, but if you’re not going to remove this, you have to do some renaming
git remote rm origin 

# This is my repo in this command, but you can recreate (delete, then create) your repo so you can still have "mochapack"
git remote add origin https://github.com/akosipax/mochapack.git
```

See the result in my own account: https://github.com/akosipax/mochapack

It has the commit history + no note about it on top being a fork. I do believe that git history is valuable. Having the git history will point us right away to the appropriate issues, and PRs.

Or maybe faster for you would be for me to transfer my repo's ownership to yours. Either way, you'd have to delete this repo to prevent name clashing. What do you think?

**Comment by vlasenko** [comment]
Thanks @alecf and @akosipax. The history from `mocha-webpack` repository has been transferred into this repo.
