### ISSUE TITLE
A better example please [Feature]

### ISSUE THREAD

**Issue by visualjeff** [sysgears/mochapack#41]
Would it be possible to update the example demonstrating how we can actually test functions loaded from a separate js file via script tag?  

Just the basic example... The HTML page imports a script using a script tag.  The mocha test script will test/exercise the functions in the external script (the HTML file loads via the script tag).   The example provided in the source exercises Mocha but doesn't look as if its testing any functions that would be loaded via script tag.

Thanks for listening!

**Comment by larixer** [comment]
@visualjeff To which example do you refer?

**Comment by visualjeff** [comment]
Located within the source at examples/debug-webpack4

Thanks for responding.
