### ISSUE TITLE
[Bug] Webpack env vars are passed incorrectly

### ISSUE THREAD

**Issue by zjxiaohan** [sysgears/mochapack#42]
- [x] I'd be willing to submit the fix

**Describe the bug**

When running `node bin/_mocha --webpack-config test/integration/cli/fixture/config/config.env.js --webpack-env.test 0.96726147776912 "test/integration/cli/fixture/simple/simple.js"`, the environment variable `test/integration/cli/fixture/config/config.env.js` receives is `{ test: [ '0.96726147776912', '0.96726147776912' ] }` instead of ``{ test: '0.96726147776912' }``.

**To Reproduce**

To reproduce, run the `passes --webpack-env object to config` test in `/test/integration/cli/config.test.js` and print the `env`.

**Screenshots**

There are no real screenshots. I tried to print `parsedArgs` in the `parse` function in `/src/cli/parseArgv`, and the content doesn't seem correct.

![Screenshot from 2019-11-25 14-27-10](https://user-images.githubusercontent.com/20266703/69518725-3a3e6c00-0f93-11ea-8457-cd54ca543103.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version 10.16.3
 - Mochapack version 1.1.10
 - Webpack version 4.41.0

**Additional context**

Not sure if this is related:

https://github.com/sysgears/mochapack/blob/41cb27512f86d4f24127f6605b7404b839e6e1c7/src/cli/parseArgv.js#L295-L298

**Comment by larixer** [comment]
@zjxiaohan Yep, I think that code is related

**Comment by zjxiaohan** [comment]
@larixer Thanks for your prompt response. Yeah I didn't look into it closely but it looks like it's going to get the first element of the array and put it into the env. However, when testing by myself, I don't see these lines being run and the `env` passed into the webpack config is wrong.
