### ISSUE TITLE
[Bug] Promised webpack config is not resolved

### ISSUE THREAD

**Issue by Jack-Barry** [sysgears/mochapack#44]
- [x] I'd be willing to submit the fix

**Describe the bug**

A Promised Webpack config is not resolved before `mochapack` uses it.

**To Reproduce**

Set the `--webpack-config` to a Webpack config that returns a Promise.

I have a project set up here: [`electron-playground`](https://github.com/Jack-Barry/electron-playground). Once cloned:

```bash
npm i
npm run test:unit
```

**Screenshots**

![Screen Shot 2019-11-29 at 21 39 50](https://user-images.githubusercontent.com/8129489/69895193-0e075000-12f1-11ea-9901-d30d4f3207d7.png)

You'll notice that Webpack begins compiling before it has resolved the config, as evidenced by the timing of the executed `console.log`.

**Environment if relevant (please complete the following information):**

 - OS: macOS Catalina `10.15.1`
 - Node version `v12.8.1`
 - Mochapack version `1.1.12`
 - Webpack version `4.41.2`

**Additional context**

In my use case, I'm trying to use a Webpack config from `electron-webpack` that relies on a resolved Promise for the config. I'm not sure where to look exactly to fix this, but I'd imagine it basically involves just `await`ing the config from whatever `--webpack-config` is pointed at before proceeding to run `webpack`. Happy to help if I can!

**Comment by larixer** [comment]
I believe await can be done on this line:
https://github.com/sysgears/mochapack/blob/adcd4ccf7dc1dba6b071166d9dcf61b9e5b5ad42/src/cli/requireWebpackConfig.js#L106
and async await should be propagated the chain of callers of `requireWebpackConfig`
