### ISSUE TITLE
[Bug] useColor deprecation warnings with mocha@7.0

### ISSUE THREAD

**Issue by andykais** [sysgears/mochapack#53]
- [ ] I'd be willing to submit the fix

**Describe the bug**

I am seeing some warnings when running mochapack only visible when using `mocha@7.0.0` and higher. `mocha@6.2.2` and lower do not show it.
```
> mochapack --interactive=false src/**/*.unit.test.ts

 WEBPACK  Compiling...

 WEBPACK  Compiled successfully in 1170ms

 MOCHA  Testing...



(node:366166) DeprecationWarning: "useColors()" is DEPRECATED, please use "color()" instead.
(node:366166) DeprecationWarning: "useInlineDiffs()" is DEPRECATED, please use "inlineDiffs()" instead.
  src/dsl-parser/__tests__/dsl.unit.test.ts
ran
    ✓ mytest


  1 passing (16ms)

 MOCHA  Tests completed successfully
```

this does not affect test behavior, but I assume these warnings are because an older mocha color scheme is being used.

**To Reproduce**
```
npm install mochapack mocha@7
```
and run mochapack on any test

 - OS: [e.g. OSX, Linux, Windows, ...] archlinux
 - Node version [e.g. 8.15.0, 10.15.1, ...] `v13.8.0`
 - Mochapack version [e.g. 1.1.3, ...] `1.1.13`
 - Webpack version [e.g. 4.26.1, ...] `4.41.5`

**Additional context**

**Comment by aparajita** [comment]
That's probably why they declare the mocha peerDependency as ">=4 <=6". Would be great to fix this and dump the peerDependency version to 7.

**Comment by andykais** [comment]
Hey all, I think this may be related to the upgrade. I don't see colors on mocha/chai output anymore:
![screenshot(226)](https://user-images.githubusercontent.com/6627147/80314129-9533f380-87bd-11ea-8245-7f27e96397bf.png)

![screenshot(228)](https://user-images.githubusercontent.com/6627147/80314140-b0066800-87bd-11ea-974e-0bf810dc7f3f.png)

I can create a separate issue if that is appropriate

**Comment by aparajita** [comment]
@andykais Yes, please make a separate issue.
