### ISSUE TITLE
Multiple reporters support

### ISSUE THREAD

**Issue by yuanhao** [sysgears/mochapack#6]
Is it possible to add the multiple reporters support in mochapack? Since mocha has supported it (https://github.com/mochajs/mocha/pull/1360).

Currently got the error "Error: Duplicating arguments for "--reporter" is not allowed. "--reporter spec --reporter xunit" was provided, but expected "--reporter spec"".

**Comment by vlasenko** [comment]
@yuanhao Yep, I think this one is very straightforward enhancement

**Comment by vlasenko** [comment]
@yuanhao Actually according to the link you have in your top post the mocha does not support multiple reporters. So I'm closing this issue. Lets revisit it when mocha will support multiple reporters
