### ISSUE TITLE
[Bug] gitbook-plugin-github specified twice in dependencies

### ISSUE THREAD

**Issue by jayaddison** [sysgears/mochapack#61]
**Describe the bug**

This is a duplicate of a previous issue https://github.com/sysgears/mochapack/issues/40.

it looks like the `gitbook-plugin-github` dependency [appears](https://github.com/sysgears/mochapack/blob/ad601b9deb96445263a7a3cc818ffb61a1a75442/package.json#L92) [twice](https://github.com/sysgears/mochapack/blob/ad601b9deb96445263a7a3cc818ffb61a1a75442/package.json#L114) in `package.json`.

**Comment by larixer** [comment]
I don't know why, but `npm publish` adds this `gitbook-plugin-github` dependency. Published `mochapack@1.1.15` via `yarn publish`

**Comment by jayaddison** [comment]
Puzzling.. I took a quick look in the NPM CLI open issues, and wondered if https://github.com/npm/cli/issues/1018 might be related.  Not certain though.  Thanks for the quick fix-up here!
