### ISSUE TITLE
v2.0.0 - Config

### ISSUE THREAD

**Issue by dsrini-open** [sysgears/mochapack#67]
Hi, 

I am confused as to how to use mochapack v2.0.0. Any doc would be useful on how to pass the config, and what config options are available. Previously, I used mochapack.opts file and provided the same as cli args - 
> mochapack --opts test/mochapack.opts

The file contents include 
```
--require "@babel/register"
--require "jsdom-global/register"
--require "test/setup.js"
--recursive
"src/**/test/**/*.spec.js" "src/**/*.vue"
--reporter "spec"
--webpack-config test/webpack.config.js
```

Now, if I run the same way I get exception - WebpackOptionsValidationError: Invalid configuration object.

Tried with 
> mochapack --webpack-config test/webpack.config.js

Now, webpack config is loaded properly, but how/where do you specify my root .mocharc.json file. Contents are below - 
```
{
  "extension": ["js", "vue"],
  "require": ["@babel/register", "jsdom-global/register", "test/setup.js"],
  "reporter": "spec",
  "spec": ["src/**/test/**/*.spec.js", "src/**/*.vue"],
  "recursive": true
}
```

The problem with mocharc.json file in root folder - No tests are running. 

@Jack-Barry -> Thanks for all your help!

**Comment by Jack-Barry** [comment]
@dsrini-open Do you have a repo that I can clone that reproduces the issue?

Thanks

**Comment by dsrini-open** [comment]
Please find the test repo [here](https://github.com/dsrini-open/test-mp).

My questions are primarily how do you set config with/for mochapack - 
- Where/how you specify the webpack-config file other than cli args. 
- How do you pass the mocha config file?

Thanks!

**Comment by dsrini-open** [comment]
Resolved the issue by passing the following config in **package.json** scripts under test - 
`NODE_ENV=test mochapack --config .mocharc.json --webpack-config test/webpack.config.js \"src/**/test/**/*.spec.js\"`

I had to pass the location of mocha config file and webpack config file with the glob to run the tests. Now, the mocha config file contains --require scripts.

**Comment by Jack-Barry** [comment]
@dsrini-open Thank you for sharing, glad you were able to resolve the issue

Would you be willing to write up some notes for the README about your findings? I will probably not be able to get around to it for a couple of weeks at least

**Comment by thom-nic** [comment]
I ran into this issue as well.  `--opts` is not handled properly with mocha v7 nor does it pick up the default `.mocharc.js` when running through mochapack.  But passing `--config .mocharc.js --webpack-config ____` got it to work.

```
± npm ls mochapack mocha
├── mocha@7.2.0 
└── mochapack@2.0.3 
```
