### ISSUE TITLE
Warning: the engine "pm" appears to be invalid

### ISSUE THREAD

**Issue by JordanMajd** [sysgears/mochapack#69]
- [x] I'd be willing to submit the fix

**Describe the bug**

`yarn install` on a project using `mochapack@2.0.0` produces a warning `warning mochapack@2.0.0: The engine "pm" appears to be invalid.`

**To Reproduce**

```sh
yarn init
yarn add -D mochapack
yarn install
```

**Environment if relevant (please complete the following information):**

 - OS: OSX (macOS Catalina)
 - Node version v13.12.0
 - Mochapack version  2.0.0
 - Webpack version 4.43.0

**Comment by dsrini-open** [comment]
I remember seeing this issue, forgot exactly what I did - but guess updated yarn/node/npm or added mocha/webpack. - Tried in a new repo - not getting it anymore!

**Comment by larixer** [comment]
Should be fixed in `mochapack@2.0.1`
