### ISSUE TITLE
Update docs/dependencies to include mocha 6.0.0?

### ISSUE THREAD

**Issue by eponymous301** [sysgears/mochapack#7]
I've tried mochapack with mocha 6.0.0 and it seems to work fine.

**Comment by vlasenko** [comment]
@eponymous301 Thank you! Will do

**Comment by vlasenko** [comment]
@eponymous301 Have you tried to clone this repo, update mocha to version 6 and run the tests? I see multiple failures. Some 3rd party deps used by `mochapack` have not been upgraded to mocha 6 yet, for example `bdd-lazy-var` supports mocha only up to `mocha 5.2.x`. So it is probably not a good time now to upgrade to mocha 6 yet...

**Comment by vlasenko** [comment]
Resolved in #8

**Comment by vlasenko** [comment]
Released in `mochapack@1.1.0`
