### ISSUE TITLE
[Feature] WebStorm testing framework integration

### ISSUE THREAD

**Issue by pkqxdd** [sysgears/mochapack#74]
- [x] I'd be willing to implement this feature

On WebStorm, one can run tests in a `.spec.ts` file inside the IDE. This provides the advantage of integrating with the existing editor as well as jumping to different parts of the project when some tests inevitably fail. 

Currently, WebStorm cannot reliably detect `mochapack` as a `mocha` package because of the lack of `mocha` file in the `bin` folder. Other `mocha` replacements, such as `electron-mocha` can be detected by the IDE. This issue can be solved by either renaming the executable from `mochapack` to `mocha`, or symlinking `mocha` to `mochapack` in the `bin` folder. 

This fix should fit the ideology of the project better as a drop-in replacement of `mocha`

**Comment by pkqxdd** [comment]
Screenshot of a working configuration by using a symlink
<img width="1400" alt="Screen Shot 2020-06-22 at 4 47 37 PM" src="https://user-images.githubusercontent.com/24923261/85345745-28309780-b4a8-11ea-90cd-ef24bec2ecb8.png">

**Comment by larixer** [comment]
Should be fixed in `mochapack@2.0.1` via #68
