### ISSUE TITLE
[Bug] v2.0.1 breaks testing in Nuxt project

### ISSUE THREAD

**Issue by AbleLincoln** [sysgears/mochapack#75]
- [ ] I'd be willing to submit the fix

**Describe the bug**

v2.0.1 breaks testing for Nuxt project (with Vuetify). This may be happening with other frameworks/setups, but I discovered this bug with a Nuxt project. Essentially, the tests no longer run. mochapack is able to succesfully compile the project, but it doesn't run any of the tests. It just completes with "0 passing".

I think I have narrowed this down to the change addressed in  [this commit](https://github.com/sysgears/mochapack/pull/70). `chunk.isOnlyInitial()` properly chunks the modules, but `chunk.hasEntryModule()` appears to only pass for a single chunk.

**To Reproduce**

See [this repo](https://github.com/AbleLincoln/mochapack-2..0.1-bug)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: 12.16.3
 - Mochapack version: 2.0.1
 - Webpack version: 4.43.0

**Comment by AbleLincoln** [comment]
btw, I am able to fix this problem by locking mochapack at `v2.0.0`

**Comment by AbleLincoln** [comment]
I'm not sure if this is related, but I also came across [this solution](https://github.com/zinserjan/mocha-webpack/issues/48#issuecomment-472094866) for a similar issue with mocha-wepack. Apparently `optimization.runtimeChunk = "single"` and mocha do not play nicely together.

**Comment by larixer** [comment]
@AbleLincoln Thanks, I've rolled back PR #70 for now to fix this issue and published `mochapack@2.0.2`

**Comment by AbleLincoln** [comment]
Still getting this issue in `v2.0.2`. It looks like the build didn't work for some reason. The published JS files still have broken the code from `2.0.1`.

**Comment by larixer** [comment]
@AbleLincoln Published `mochapack@2.0.3`, could you check and report back, please?

**Comment by AbleLincoln** [comment]
Works great! Thank you 🙂

**Comment by larixer** [comment]
Thank for letting know!
