### ISSUE TITLE
[Bug] SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by jcjp** [sysgears/mochapack#76]
- [ ] I'd be willing to submit the fix

**Describe the bug**

I have a Nuxt application with a library of @adonisjs/websocket-client, when I compile it with Nuxt it works but when I use to test my application using mochapack it runs into an error of: SyntaxError: Unexpected token 'export' here is the full error:

```
node_modules/@adonisjs/websocket-client/dist/Ws.es.js:2507
export default index;
^^^^^^

SyntaxError: Unexpected token 'export'
```

**To Reproduce**

1. Create a nuxt app using `npx create-nuxt-app <app-name>` or `yarn create nuxt-app <app-name>`
2. Then install `@adonisjs/websocket-client`
3. Import Ws from `@adonisjs/websocket-client` in pages/index.vue
4. Configure mochapack to be able to test Nuxt app here is a link to set it up: [Setup for Vue and Mochapack](https://vue-test-utils.vuejs.org/guides/testing-single-file-components-with-mocha-webpack.html)
5. Run test and the error will occur

Here is a more details result of the error:
```
➜ npm run test

> nuxt-mochapack@1.0.0 test .../nuxt-mochapack
> mochapack

 WEBPACK  Compiling...

  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 756ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

.../nuxt-mochapack/node_modules/@adonisjs/websocket-client/dist/Ws.es.js:2507
export default index;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:891:16)
    at Module._compile (internal/modules/cjs/loader.js:941:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Object.module_1.default._extensions.<computed> [as .js] (.../nuxt-mochapack/node_modules/mochapack/src/util/registerRequireHook.ts:99:53)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 20.04
 - Node version: 13.0.1
 - Mochapack version: ^1.1.13
 - Webpack version: (Not sure what version Nuxt is using)

**Additional context**

Remove some information replaced them with `...` for brevity. I also tried the configuring my mochapack.config.js with `esModule: false` options for `file-loader` but that did not do the trick. Just some more information Nuxt uses webpack as well and it compiles and run the application without any issues, only when I try to run the test with mochapack.

**Comment by quangkevin** [comment]
This fix doesn't require a PR. Just use babel to transform ES6 to CommonJS. Specifically, configure your setup.js file to do something like this:

require("@babel/register")({
  plugins: ["@babel/plugin-transform-modules-commonjs"],
});

See https://babel.dev/docs/en/babel-register for configuration options.

**Comment by larixer** [comment]
@quangkevin Do you mean no changes should be done on `mochapack` side and its the matter of Nuxt application configuration instead?

**Comment by quangkevin** [comment]
Hi @larixer The change should be done outside of mochapack.

```
mochapack --require setup.js ...
```
setup.js:
```
require("@babel/register")({
  plugins: ["@babel/plugin-transform-modules-commonjs"],
});
```
