### ISSUE TITLE
[Feature] Webpack v5 compatibility

### ISSUE THREAD

**Issue by jayaddison** [sysgears/mochapack#82]
- [x] ~~I'd be willing to implement this feature~~ I tried to implement this feature but did not achieve completion; see #83

**Describe the user story**
`webpack` v5.0.0 was [released on 2020-10-10](https://webpack.js.org/blog/2020-10-10-webpack-5-release/) and is likely to see gradual uptake as new projects begin using it and existing projects migrate to it.  As a user of `webpack` v4 and `mochapack`, I'd appreciate the ability to have an upgrade path for my project in order to run tests based on `webpack` v5.

**Describe the solution you'd like**
Upgrades to the `mochapack` CLI to support projects using `webpack` v5.

**Describe the drawbacks of your solution**
`webpack` v5 introduces a number of breaking changes, and it's unclear to me whether it would be possible to support *both* v4 and v5 from an updated `mochapack` codebase.

**Comment by jayaddison** [comment]
As a heads-up to anyone following this issue and keen to see it resolved; it's being worked on in #83, but progress is slow since I don't have much expertise in this codebase and - to be fairly honest about it - it is not yet a blocker or high-priority feature for the project I'm working on, so it tends to fall below other priorities.

Hopefully there'll be a good reason to kickstart further progress soon; in the meantime if anyone's getting a sense that their own work is unnecessarily delayed or blocked waiting for `webpack` v5 support in `mochapack`, your contributions and ideas for how to get this implemented are welcome.

**Comment by privatenumber** [comment]
I made [instant-mocha](https://github.com/privatenumber/instant-mocha) which has support for Webpack 5.

**Comment by larixer** [comment]
@privatenumber In my opinion it is not ethical to write "consider switching" on an issue tracker of another project, especially, when you created the project to which you ask to switch 24 hours ago. It's also not ethical to write about the "over-engineered implementation and convoluted code" of the other project in your readme when you have neither feature-parity nor user-base of a similar size served for a long time.

**Comment by privatenumber** [comment]
Thanks for calling out @larixer. I must've been too excited to get the word out. I reworded it to be more considerate of the situation.

If instant-mocha doesn't have feature parity, please let me know the specifics and I can look into it. It has unblocked me from upgrading to Webpack 5 and would love to help others make that progress too.

**Comment by larixer** [comment]
@privatenumber Sounds good, let us see how things will go when more people use your solution

**Comment by serut** [comment]
I've migrated my app (3K tests) to instant-mocha and it's working so far. It's looks like there is less magic between the test runner and the app, so I rewrited some tests (setTimeout inside my react component was blocking test execution), but otherwise it works quite well upon Webpack 5.

**Comment by privatenumber** [comment]
Thanks for testing @serut 

TBH, I don't think mocha-webpack has any magic to handle special cases. I think what happened was that either mocha-webpack, Webpack 4, or an older version of Mocha (if you upgraded that too) wasn't correctly handling something, and a bug in your tests slipped through the cracks.

instant-mocha surfacing that bug is an improvement IMO 👍

**Comment by larixer** [comment]
The support has been added by @sodatea and included into `mochapack@2.1.0`, which has just been published
