### ISSUE TITLE
[Bug] Webpack 5 warns about absolute paths on Windows

### ISSUE THREAD

**Issue by sebamarynissen** [sysgears/mochapack#99]
- [x] I'd be willing to submit the fix

I am using mochapack in a project of mine and recently upgraded to webpack 5. The migration was succesful thanks to the newly released version. Thanks for the great work!

There's one minor issue though that I encountered during the migration. Webpack 5 gives the following warning when running the tests:
```
Warning in ./node_modules/mochapack/lib/entry.js

  Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
  Invalid dependencies may lead to broken watching and caching.
  As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
  Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
  Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
  Globs: They are not supported. Pass absolute path to the directory as context dependencies.
  The following invalid values have been reported:
   * "C:/Users/my/test/file.js"
```

The reason is that webpack fails to recognize that `C:/Users/my/test/file.js` is an absolute path, as it expects it to be `C:\Users\my\test\file.js`.

I've been able to fix it by modifying `entryLoader.ts` by doing
```ts
import path from 'path';

const entries = config.getFiles().map(file => path.normalize(file));
```
See also https://github.com/sysgears/mochapack/blob/master/src/webpack/loader/entryLoader.ts#L35.

Alternatively I think it should also be possible to just use `path.normalize()` instead of the `normalize-path` module:
```ts
export class EntryConfig {
  files: Array<string>

  constructor() {
    this.files = []
  }

  addFile(file: string): void {
    const normalizedFile = path.normalize(file)
    this.files.push(normalizedFile)
  }

  removeFile(file: string): void {
    const normalizedFile = path.normalize(file)
    this.files = this.files.filter(f => f !== normalizedFile)
  }

  getFiles(): Array<string> {
    return this.files
  }
}
```

**To Reproduce**

Run mochapack on Windows with Webpack 5.

**Environment:**

 - OS: Windows 10
 - Node version: 14.15.5
 - Mochapack version: 2.1.0
 - Webpack version: 5.37.0

**Comment by larixer** [comment]
@sebamarynissen Thanks for the bug rreport. Feel free to open a Pull Request, since seems you already found the way how to solve the issue

**Comment by sebamarynissen** [comment]
@larixer PR created (#100). I had to go with the second option of modifying the `EntryConfig` class because the tests relied on it.
